spring:
  application:
    name: notification-service
  datasource:
    url: ${NOTIFICATION_DB_URL:jdbc:postgresql://localhost:5435/notification_db}
    username: ${NOTIFICATION_DB_USERNAME:notification_user}
    password: ${NOTIFICATION_DB_PASSWORD:notification_password}
  jpa:
    hibernate:
      ddl-auto: none
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:rabbitmq}
    password: ${RABBITMQ_PASSWORD:rabbitmq}
server:
  port: ${NOTIFICATION_SERVICE_PORT:8083}


