spring:
  application:
    name: product-service
  datasource:
    url: ${PRODUCT_DB_URL:jdbc:postgresql://localhost:5433/product_db}
    username: ${PRODUCT_DB_USERNAME:product_user}
    password: ${PRODUCT_DB_PASSWORD:product_password}
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: ${PRODUCT_SERVICE_PORT:8081}


